# Generated by Django 5.2 on 2025-05-18 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_type', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=255)),
                ('input_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Pregnancies', models.IntegerField(blank=True, null=True)),
                ('Glucose', models.FloatField(blank=True, null=True)),
                ('BloodPressure', models.FloatField(blank=True, null=True)),
                ('SkinThickness', models.FloatField(blank=True, null=True)),
                ('Insulin', models.FloatField(blank=True, null=True)),
                ('BMI', models.FloatField(blank=True, null=True)),
                ('DiabetesPedigreeFunction', models.FloatField(blank=True, null=True)),
                ('DiabetesAge', models.IntegerField(blank=True, null=True)),
                ('heart_age', models.IntegerField(blank=True, null=True)),
                ('sex', models.IntegerField(blank=True, null=True)),
                ('cp', models.IntegerField(blank=True, null=True)),
                ('trestbps', models.FloatField(blank=True, null=True)),
                ('chol', models.FloatField(blank=True, null=True)),
                ('fbs', models.IntegerField(blank=True, null=True)),
                ('restecg', models.IntegerField(blank=True, null=True)),
                ('thalach', models.FloatField(blank=True, null=True)),
                ('exang', models.IntegerField(blank=True, null=True)),
                ('oldpeak', models.FloatField(blank=True, null=True)),
                ('slope', models.IntegerField(blank=True, null=True)),
                ('ca', models.IntegerField(blank=True, null=True)),
                ('thal', models.IntegerField(blank=True, null=True)),
                ('kidney_age', models.IntegerField(blank=True, null=True)),
                ('bp', models.FloatField(blank=True, null=True)),
                ('sg', models.FloatField(blank=True, null=True)),
                ('al', models.IntegerField(blank=True, null=True)),
                ('su', models.FloatField(blank=True, null=True)),
                ('bgr', models.FloatField(blank=True, null=True)),
                ('bu', models.FloatField(blank=True, null=True)),
                ('sc', models.FloatField(blank=True, null=True)),
                ('sod', models.FloatField(blank=True, null=True)),
                ('pot', models.FloatField(blank=True, null=True)),
                ('hemo', models.FloatField(blank=True, null=True)),
                ('pcv', models.IntegerField(blank=True, null=True)),
                ('wc', models.FloatField(blank=True, null=True)),
                ('rc', models.FloatField(blank=True, null=True)),
                ('liver_Age', models.IntegerField(blank=True, null=True)),
                ('Gender', models.CharField(blank=True, max_length=1, null=True)),
                ('Total_Bilirubin', models.FloatField(blank=True, null=True)),
                ('Direct_Bilirubin', models.FloatField(blank=True, null=True)),
                ('Alkaline_Phosphotase', models.FloatField(blank=True, null=True)),
                ('Alamine_Aminotransferase', models.FloatField(blank=True, null=True)),
                ('Aspartate_Aminotransferase', models.FloatField(blank=True, null=True)),
                ('Total_Proteins', models.FloatField(blank=True, null=True)),
                ('Albumin', models.FloatField(blank=True, null=True)),
                ('Albumin_and_Globulin_Ratio', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
